### ISSUE TITLE
Security issue : Attendance can be messed up by using Postman.

### ISSUE THREAD

**Issue by Ananthusubramanian** [amfoss/join-foss#7]
Getting the fetched wifi SSID from the server and passing it to the API marks the attendance. Instead of wifi SSID, the location and face recognition can be accessed (Opinion).
![untitled](https://user-images.githubusercontent.com/22250995/40484018-b50d7b74-5f77-11e8-9439-3bfc55209a28.png)

**Comment by chirath02** [comment]
Thank you for reporting this issue. There is not an accurate way to get the location on a laptop and it would be okay to implement but face detection. But both of these methods can easily be faked. I will be working on a better fix when I get time.

**Comment by Ananthusubramanian** [comment]
@chirath02  I am interested in making an Android app for attendance and the idea works on accessing the location (latitude and longitude) with face recognition and if both this is true, then it marks up attendance. On signup, the name of the person can be trained by getting pictures and then the length of cheeks and much more can be saved in the database. And after when attendance button is clicked, the difference between the foss lab location and the exact location (latitude and longitude) will be treated as an argument and the next would be recognizing the face.
Refrence:
For Location:https://goo.gl/fGX363
For Face recongnition:https://developers.google.com/vision/android/detect-faces-tutorial
Sample Gitup projects:
https://github.com/googlesamples/android-vision/tree/master/visionSamples/FaceTracker
